apiVersion: v1
kind: ConfigMap
metadata:
  name: relay
  labels:
    app: relay
data:
  config.yml: |-
    relay:
      mode: managed
      upstream: "https://{{ .Values.ingress.host}}:{{ .Values.service.externalPort }}/"
      host: 0.0.0.0
      port: 3000
    processing:
      enabled: true
      kafka_config:
        - name: "bootstrap.servers"
          value: {{ (include "sentry.kafka.bootstrap_servers_string" .) | quote }}
        - name: "message.max.bytes"
          value: 50000000  # 50MB or bust
      redis: "redis://:{{ .Values.redis.redisPassword }}@{{ template "redis.fullname" . }}:6379"
