apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-snuba-api
  labels:
    app: sentry
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
      release: "{{ .Release.Name }}"
      role: snuba-api
  template:
    metadata:
      annotations:
        checksum/snubaSettingsPy: {{ .Values.config.snubaSettingsPy | sha256sum }}
        checksum/config.yaml: {{ include (print $.Template.BasePath "/configmap-snuba.yaml") . | sha256sum }}
        {{- if .Values.snuba.api.annotations }}
{{ toYaml .Values.snuba.api.annotations | indent 8 }}
        {{- end }}
      labels:
        app: {{ template "fullname" . }}
        release: "{{ .Release.Name }}"
        role: snuba-api
        {{- if .Values.snuba.api.podLabels }}
{{ toYaml .Values.snuba.api.podLabels | indent 8 }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-snuba
        image: "{{required ".Values.global.dockerHubMirror is missing" .Values.global.dockerHubMirror }}/{{ .Values.image.snuba.repository }}:{{required ".Values.image.snuba.tag is missing" .Values.image.snuba.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.image.snuba.pullPolicy }}
      {{- if .Values.snuba.api.command }}
        command:
{{ toYaml .Values.snuba.api.command | indent 8 }}
      {{- end }}
        ports:
        - containerPort: {{ template "snuba.port" }}
        env:
{{ include "sentry.snuba.env" . | indent 8 }}
{{- if .Values.snuba.api.env }}
{{ toYaml .Values.snuba.api.env | indent 8 }}
{{- end }}
        envFrom:
        - secretRef:
            name: {{ template "fullname" . }}-snuba-env
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: {{ template "snuba.port" }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.snuba.api.probeInitialDelaySeconds }}
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: {{ .Values.snuba.api.liveness.timeoutSeconds }}
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: {{ template "snuba.port" }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.snuba.api.probeInitialDelaySeconds }}
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: {{ .Values.snuba.api.readiness.timeoutSeconds }}
        resources:
{{ toYaml .Values.snuba.api.resources | indent 12 }}
{{- if .Values.snuba.api.sidecars }}
{{ toYaml .Values.snuba.api.sidecars | indent 6 }}
{{- end }}
