apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-worker
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.workerReplicaCount }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-worker
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-worker
        alert-tier: os
        alert-service: sentry
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{required ".Values.global.dockerHubMirror is missing" .Values.global.dockerHubMirror }}/{{ .Values.image.sentry.repository }}:{{required ".Values.image.sentry.tag is missing" .Values.image.sentry.tag }}"
        imagePullPolicy: {{ .Values.image.sentry.pullPolicy }}
        args: [ run, worker ]
        env:
{{ include "env-vars" . | indent  10 }}
